apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloudacademy
  labels:
    role: frontend
    env: demo
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: cloudacademydevops/stocks-app:v2
        imagePullPolicy: Always
        env:
          - name: REACT_APP_APIHOSTPORT
            value: INGRESS_FQDN
          - name: NGINX_APP_APIHOSTPORT
            value: api.cloudacademy.svc.cluster.local:8080
        ports:
        - containerPort: 8080
