apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: cloudacademy
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: followthewhiterabbit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cloudacademy
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: cloudacademydevops/stocks-api:v2
        imagePullPolicy: Always
        env:
          - name: DB_CONNSTR
            value: jdbc:mysql://RDS_AURORA_ENDPOINT:3306/cloudacademy
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: DB_PASSWORD
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: cloudacademy
  labels:
    role: api
    env: demo
spec:
  ports:
   - protocol: TCP
     port: 8080
  selector:
    role: api